Feat/vm logger
Pivot-Studio/pivot-lang pull request #260
Opened 2023-03-28 15:59 UTC by MoonOld

implements a much lighter logger than env_logger to avoid too much burden resulted by vm lib linking
now supports
* read log level from env
* log with timestamp

2023-03-28 16:03 UTC, MoonOld commented on Cargo.lock
自动生成的你懂个鸡毛

2023-03-28 16:51 UTC, Chronostasys requested changes

2023-03-28 16:51 UTC, Chronostasys commented on vm/src/gc/mod.rs
> +
去了

2023-03-28 16:51 UTC, Chronostasys commented on vm/src/logger/mod.rs
> +    ///
为啥开头多加一行

2023-03-28 16:51 UTC, Chronostasys commented on vm/src/logger/mod.rs
> +    // fn init(logger:Self) {
这种都去掉

2023-03-29 07:49 UTC, Chronostasys requested changes

2023-03-29 08:33 UTC, Chronostasys approved these changes
LGTM!

2023-03-29 08:33 UTC, merged